name: abc_kids
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_launcher_icons: ^0.7.3
  audioplayers: ^0.13.2
  speech_recognition: ^0.3.0+1
  bloc_pattern: ^1.3.0
  permission_handler: ^3.2.2
  connectivity: ^0.4.4
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.0.7
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.6
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  auto_size_text: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

flutter_icons:
  android: true 
  ios: true
  image_path: "images/logoRedonda.png"

flutter:
  fonts:
  - family: FunnyKid
    fonts:
      - asset: fontes/FunnyKid.ttf

  - family: PatuaOne
    fonts:
      - asset: fontes/PatuaOne-Regular.ttf
  
  - family: RubikMono
    fonts:
      - asset: fontes/RubikMonoOne-Regular.ttf

  - family: SnigletRegular
    fonts:
      - asset: fontes/Sniglet-Regular.ttf

  - family: Sniglet-ExtraBold
    fonts:
      - asset: fontes/Sniglet-ExtraBold.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/planoDeFundoOficialSemLogo.jpeg
    - images/brazil.png
    - images/eua.png
    - images/spain.png
    - images/logoRedonda.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/4.png
    - images/5.png
    - images/house.png
    - images/aprenderAlfabeto.png
    - images/digitarPalavra.png
    - images/falarPalavra.png
    - images/lerPalavra.png
    - assets/audios/musicaDeFundo.mp3
    - assets/audios/som_botao.mp3
    - assets/audios/alfabeto_espanhol/a.mp3
    - assets/audios/alfabeto_espanhol/b.mp3
    - assets/audios/alfabeto_espanhol/c.mp3
    - assets/audios/alfabeto_espanhol/d.mp3
    - assets/audios/alfabeto_espanhol/e.mp3
    - assets/audios/alfabeto_espanhol/f.mp3
    - assets/audios/alfabeto_espanhol/g.mp3
    - assets/audios/alfabeto_espanhol/h.mp3
    - assets/audios/alfabeto_espanhol/i.mp3
    - assets/audios/alfabeto_espanhol/j.mp3
    - assets/audios/alfabeto_espanhol/k.mp3
    - assets/audios/alfabeto_espanhol/l.mp3
    - assets/audios/alfabeto_espanhol/m.mp3
    - assets/audios/alfabeto_espanhol/n.mp3
    - assets/audios/alfabeto_espanhol/o.mp3
    - assets/audios/alfabeto_espanhol/p.mp3
    - assets/audios/alfabeto_espanhol/q.mp3
    - assets/audios/alfabeto_espanhol/r.mp3
    - assets/audios/alfabeto_espanhol/s.mp3
    - assets/audios/alfabeto_espanhol/t.mp3
    - assets/audios/alfabeto_espanhol/u.mp3
    - assets/audios/alfabeto_espanhol/v.mp3
    - assets/audios/alfabeto_espanhol/w.mp3
    - assets/audios/alfabeto_espanhol/x.mp3
    - assets/audios/alfabeto_espanhol/y.mp3
    - assets/audios/alfabeto_espanhol/z.mp3
    - assets/audios/alfabeto_portugues/a.mp3
    - assets/audios/alfabeto_portugues/b.mp3
    - assets/audios/alfabeto_portugues/c.mp3
    - assets/audios/alfabeto_portugues/d.mp3
    - assets/audios/alfabeto_portugues/e.mp3
    - assets/audios/alfabeto_portugues/f.mp3
    - assets/audios/alfabeto_portugues/g.mp3
    - assets/audios/alfabeto_portugues/h.mp3
    - assets/audios/alfabeto_portugues/i.mp3
    - assets/audios/alfabeto_portugues/j.mp3
    - assets/audios/alfabeto_portugues/k.mp3
    - assets/audios/alfabeto_portugues/l.mp3
    - assets/audios/alfabeto_portugues/m.mp3
    - assets/audios/alfabeto_portugues/n.mp3
    - assets/audios/alfabeto_portugues/o.mp3
    - assets/audios/alfabeto_portugues/p.mp3
    - assets/audios/alfabeto_portugues/q.mp3
    - assets/audios/alfabeto_portugues/r.mp3
    - assets/audios/alfabeto_portugues/s.mp3
    - assets/audios/alfabeto_portugues/t.mp3
    - assets/audios/alfabeto_portugues/u.mp3
    - assets/audios/alfabeto_portugues/v.mp3
    - assets/audios/alfabeto_portugues/w.mp3
    - assets/audios/alfabeto_portugues/x.mp3
    - assets/audios/alfabeto_portugues/y.mp3
    - assets/audios/alfabeto_portugues/z.mp3
    - assets/audios/alfabeto_ingles/a.mp3
    - assets/audios/alfabeto_ingles/b.mp3
    - assets/audios/alfabeto_ingles/c.mp3
    - assets/audios/alfabeto_ingles/d.mp3
    - assets/audios/alfabeto_ingles/e.mp3
    - assets/audios/alfabeto_ingles/f.mp3
    - assets/audios/alfabeto_ingles/g.mp3
    - assets/audios/alfabeto_ingles/h.mp3
    - assets/audios/alfabeto_ingles/i.mp3
    - assets/audios/alfabeto_ingles/j.mp3
    - assets/audios/alfabeto_ingles/k.mp3
    - assets/audios/alfabeto_ingles/l.mp3
    - assets/audios/alfabeto_ingles/m.mp3
    - assets/audios/alfabeto_ingles/n.mp3
    - assets/audios/alfabeto_ingles/o.mp3
    - assets/audios/alfabeto_ingles/p.mp3
    - assets/audios/alfabeto_ingles/q.mp3
    - assets/audios/alfabeto_ingles/r.mp3
    - assets/audios/alfabeto_ingles/s.mp3
    - assets/audios/alfabeto_ingles/t.mp3
    - assets/audios/alfabeto_ingles/u.mp3
    - assets/audios/alfabeto_ingles/v.mp3
    - assets/audios/alfabeto_ingles/w.mp3
    - assets/audios/alfabeto_ingles/x.mp3
    - assets/audios/alfabeto_ingles/y.mp3
    - assets/audios/alfabeto_ingles/z.mp3
    - assets/audios/vogais_acento/à.mp3
    - assets/audios/vogais_acento/á.mp3
    - assets/audios/vogais_acento/â.mp3
    - assets/audios/vogais_acento/ã.mp3
    - assets/audios/vogais_acento/é.mp3
    - assets/audios/vogais_acento/ê.mp3
    - assets/audios/vogais_acento/í.mp3
    - assets/audios/vogais_acento/ó.mp3
    - assets/audios/vogais_acento/ô.mp3
    - assets/audios/vogais_acento/õ.mp3
    - assets/audios/vogais_acento/ú.mp3
    - assets/audios/audios_explicacao/audioCardAprenderPronuncia.mp3
    - assets/audios/audios_explicacao/audioCardDigitarPalavra.mp3
    - assets/audios/audios_explicacao/audioCardFalarPalavra.mp3
    - assets/audios/audios_explicacao/audioCardLerPalavra.mp3
    - assets/audios/audios_explicacao/audioEscolherIdioma.mp3
    - assets/audios/audios_explicacao/audioEscolherNivel.mp3
    - assets/audios/audios_explicacao/audioModuloDigitarPalavra.mp3
    - assets/audios/audios_explicacao/audioModuloFalarPalavra.mp3
    - assets/audios/audios_explicacao/audioModuloLerPalavra.mp3
    - assets/audios/audios_explicacao/audioParaTelaInicial.mp3
    - assets/audios/audios_explicacao/escolhaIdioma.mp3
    - assets/audios/audios_explicacao/escolhaNivel.mp3
    - assets/audios/audios_explicacao/voceAcertouVamosParaaProximaPalavra.mp3
    - assets/audios/audios_explicacao/voceErrouAPalavraTenteNovamente.mp3
    - assets/audios/audios_explicacao/voceTerminouEsteNivelEscolhaoProximoNivelParaJogar.mp3





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

